apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: course-app
  namespace: production
spec:
  interval: 1m
  chart:
    spec:
      chart: ./charts/course-app
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    replicaCount: 3
    ingress:
      enabled: true
      host: app.local
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 5
      targetCPUUtilizationPercentage: 70
