replicaCount: 1

image:
  repository: ghcr.io/saltanden/course-app
  tag: "v1"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: ghcr-secret

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  host: app.staging.local

env:
  APP_STORE: redis
  APP_REDIS_URL: redis://dragonfly:6379

resources: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

probes:
  liveness:
    path: /healthz
    initialDelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 3
  readiness:
    path: /healthz
    initialDelaySeconds: 5
    periodSeconds: 5
    failureThreshold: 3
